// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: Lock

#ifndef _LOCK_UI_H
#define _LOCK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void minimize_Animation(lv_obj_t * TargetObject, int delay);
void maximize_Animation(lv_obj_t * TargetObject, int delay);
void moveUp_Animation(lv_obj_t * TargetObject, int delay);
void moveDown_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_lockScreen
void ui_lockScreen_screen_init(void);
extern lv_obj_t * ui_lockScreen;
extern lv_obj_t * ui_lockPanel;
extern lv_obj_t * ui_digit1;
extern lv_obj_t * ui_digit2;
extern lv_obj_t * ui_digit3;
extern lv_obj_t * ui_digit4;
extern lv_obj_t * ui_progressArc;
extern lv_obj_t * ui_lockIcon;
extern lv_obj_t * ui_infoText;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_lock_png);    // assets/lock.png
LV_IMG_DECLARE(ui_img_unlock_png);    // assets/unlock.png


LV_FONT_DECLARE(ui_font_Font1);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
