// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: Lock

#include "../ui.h"

void ui_lockScreen_screen_init(void)
{
    ui_lockScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_lockScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_lockScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lockScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_infoText = lv_label_create(ui_lockScreen);
    lv_obj_set_width(ui_infoText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_infoText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_infoText, 0);
    lv_obj_set_y(ui_infoText, -30);
    lv_obj_set_align(ui_infoText, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_infoText, "Press to\nStart Unlock");
    lv_obj_set_style_text_align(ui_infoText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_infoText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lockPanel = lv_obj_create(ui_lockScreen);
    lv_obj_set_width(ui_lockPanel, 228);
    lv_obj_set_height(ui_lockPanel, 100);
    lv_obj_set_align(ui_lockPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_lockPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_lockPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_lockPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_lockPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lockPanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lockPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lockPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lockPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_digit1 = lv_label_create(ui_lockPanel);
    lv_obj_set_width(ui_digit1, 50);
    lv_obj_set_height(ui_digit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_digit1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_digit1, "O");
    lv_obj_set_style_text_align(ui_digit1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_digit1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_digit1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_digit1, lv_color_hex(0xD80000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_digit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_digit1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_digit1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_digit1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_digit1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_digit1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_digit2 = lv_label_create(ui_lockPanel);
    lv_obj_set_width(ui_digit2, 50);
    lv_obj_set_height(ui_digit2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_digit2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_digit2, "P");
    lv_obj_set_style_text_align(ui_digit2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_digit2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_digit2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_digit2, lv_color_hex(0x00BB38), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_digit2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_digit2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_digit2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_digit2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_digit2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_digit2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_digit3 = lv_label_create(ui_lockPanel);
    lv_obj_set_width(ui_digit3, 50);
    lv_obj_set_height(ui_digit3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_digit3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_digit3, "E");
    lv_obj_set_style_text_align(ui_digit3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_digit3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_digit3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_digit3, lv_color_hex(0x00BB38), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_digit3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_digit3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_digit3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_digit3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_digit3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_digit3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_digit4 = lv_label_create(ui_lockPanel);
    lv_obj_set_width(ui_digit4, 50);
    lv_obj_set_height(ui_digit4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_digit4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_digit4, "N");
    lv_obj_set_style_text_align(ui_digit4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_digit4, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_digit4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_digit4, lv_color_hex(0x00BB38), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_digit4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_digit4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_digit4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_digit4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_digit4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_digit4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_progressArc = lv_arc_create(ui_lockScreen);
    lv_obj_set_width(ui_progressArc, 200);
    lv_obj_set_height(ui_progressArc, 200);
    lv_obj_set_align(ui_progressArc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_progressArc, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_arc_set_value(ui_progressArc, 50);
    lv_arc_set_bg_angles(ui_progressArc, 0, 360);

    lv_obj_set_style_bg_color(ui_progressArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_progressArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lockIcon = lv_image_create(ui_lockScreen);
    lv_image_set_src(ui_lockIcon, &ui_img_lock_png);
    lv_obj_set_width(ui_lockIcon, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_lockIcon, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_lockIcon, 0);
    lv_obj_set_y(ui_lockIcon, 30);
    lv_obj_set_align(ui_lockIcon, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_lockIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_lockIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_lockIcon, LV_IMAGE_ALIGN_TOP_MID);
    lv_obj_set_style_image_recolor(ui_lockIcon, lv_color_hex(0x02F30A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_lockIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
